# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Country.destroy_all

COUNTRIES = {
    "Africa" => [
      {name: "Algeria", currency_name: "Algerian Dinar", capital: "Alger", airport_code: "ALG"},
      {name: "Angola", currency_name: "Angolan Kwanza", capital: "Luanda", airport_code: "LAD"},
      {name: "Benin", currency_name: "CFA Franc BCEAO", capital: "Porto-Novo", airport_code: "BNI"},
      {name: "Botswana", currency_name: "Botswana Pula", capital: "Gaborone", airport_code: "FRW"},
      {name: "Burkina Faso", currency_name: "CFA Franc BCEAO", capital: "Ouagadougou", airport_code: "OUA"},
      {name: "Burundi", currency_name: "Burundi Franc", capital: "Bujumbura", airport_code: "BJM"},
      {name: "Cameroon", currency_name: "CFA Franc BEAC", capital: "Yaound", airport_code: "DLA"},
      {name: "Cape Verde", currency_name: "Cape Verde Escudo", capital: "Praia", airport_code: "BVC"},
      {name: "Chad", currency_name: "CFA FRANC BEAC", capital: "N'Djam", airport_code: "NDJ"},
      {name: "Central African Republic", currency_name: "CFA Franc BEAC", capital: "Bangui", airport_code: "BGF"},
      {name: "Comoros", currency_name: "Comoros Franc", capital: "Moroni", airport_code: "HAH"},
      {name: "Republic of Congo", currency_name: "CFA FRANC BEAC", capital: "Brazzaville", airport_code: "BZV"},
      {name: "The Democratic Republic of Congo", currency_name: "CFA FRANC BEAC", capital: "Kinshasa", airport_code: "FIH"},
      {name: "Ivory Coast", currency_name: "CFA Franc BCEAO", capital: "Yamoussoukro", airport_code: "ABJ"},
      {name: "Djibouti", currency_name: "Djibouti Franc", capital: "Djibouti", airport_code: "JIB"},
      {name: "Egypt", currency_name: "Egyptian Pound", capital: "Cairo", airport_code: "CAI"},
      {name: "Equatorial Guinea", currency_name: "CFA FRANC BEAC", capital: "Malabo", airport_code: "SSG"},
      {name: "Eritrea", currency_name: "Nakfa", capital: "Asmara", airport_code: "ASM"},
      {name: "Ethiopia", currency_name: "Birr", capital: "Addis Abeba", airport_code: "ADD"},
      {name: "Gabon", currency_name: "CFA FRANC BEAC", capital: "Libreville", airport_code: "LBV"},
      {name: "Gambia", currency_name: "Dalasi", capital: "Banjul", airport_code: "BJL"},
      {name: "Ghana", currency_name: "Cedi", capital: "Accra", airport_code: "ACC"},
      {name: "Guinea", currency_name: "Guinea Franc", capital: "Conakry", airport_code: "CKY"},
      {name: "Guinea-Bissau", currency_name: "Guinea Bissau Peso", capital: "Bissau", airport_code:"OXB"},
      {name: "Kenya", currency_name: "Shilling", capital: "Nairobi", airport_code: "NBO"},
      {name: "Lesotho", currency_name: "Loti", capital: "Maseru", airport_code: "MSU"},
      {name: "Liberia", currency_name: "Liberian Dollar", capital: "Monrovia", airport_code: "ROB"},
      {name: "Libya", currency_name: "Libyan Dinar", capital: "Tripoli", airport_code: "TIP"},
      {name: "Madagascar", currency_name: "Malagasy Franc", capital: "Antananarivo", airport_code: "TNR"},
      {name: "Malawi", currency_name: "Malawi Kwacha", capital: "Lilongwe", airport_code: "LLW"},
      {name: "Mali", currency_name: "CFA FRANC BEAC", capital: "Bamako", airport_code: "BKO"},
      {name: "Mauritania", currency_name: "Ouguiya", capital: "Nouakchott", airport_code: "NDB"},
      {name: "Mauritius", currency_name: "Rupee", capital: "Port-Louis", airport_code: "MRU"},
      {name: "Morocco", currency_name: "Dirham", capital: "Rabat", airport_code: "CMN"},
      {name: "Mozambique", currency_name: "Metical", capital: "Maputo", airport_code: "MPM"},
      {name: "Namibia", currency_name: "Namibian Dollar", capital: "Windhoek", airport_code: "WDH"},
      {name: "Niger", currency_name: "CFA FRANC BEAC", capital: "Niamey", airport_code: "NIM"},
      {name: "Nigeria", currency_name: "Naira", capital: "Abuja", airport_code: "LOS"},
      {name: "Rwanda", currency_name: "Rawanda Franc", capital: "Kigali", airport_code: "KGL"},
      {name: "Sao Tome and Principe", currency_name: "Dobra", capital: "Sao Tome", airport_code: "TMS"},
      {name: "Senegal", currency_name: "CFA FRANC BEAC", capital: "Dakar", airport_code: "DKR"},
      {name: "Seychelles", currency_name: "Seychelle Rupee", capital: "Victoria", airport_code: "SEZ"},
      {name: "Sierra Leone", currency_name: "Leone", capital: "Freetown", airport_code: "FNA"},
      {name: "Somalia", currency_name: "Somalia Shilling", capital: "Mogadishu", airport_code: "MGQ"},
      {name: "South Africa", currency_name: "Rand", capital: "Pretoria", airport_code: "CPT"},
      {name: "South Sudan", currency_name: "South Sudanese Pound", capital: "Juba", airport_code: "JUB"},
      {name: "Sudan", currency_name: "Sudanese Pound", capital: "Khartum", airport_code: "KRT"},
      {name: "Swaziland", currency_name: "Lilangeni", capital: "Mbabane", airport_code: "SHO"},
      {name: "Tanzania", currency_name: "Tanzanian Shilling", capital: "Dodoma", airport_code: "DAR"},
      {name: "Togo", currency_name: "CFA FRANC BEAC", capital: "Lom", airport_code: "LFW" },
      {name: "Tunisia", currency_name: "Tunisiann Dollar", capital: "Tunis", airport_code: "TUN"},
      {name: "Uganda", currency_name: "Ugandan Shilling", capital: "Kampala", airport_code: "EBB"},
      {name: "Western Sahara", currency_name: "Morrocan Dinar", capital: "El-Aaiún", airport_code: "VIL"},
      {name: "Zambia", currency_name: "Zambian Kwacha", capital: "Lusaka", airport_code: "LUN"},
      {name: "Zimbabwe", currency_name: "Zimbabwe Dollar", capital: "Harare", airport_code: "HRE"}
    ],
   "Asia" => [
      {name: "Afghanistan", currency_name: "Afghanistan Afghani", capital: "Kabul", airport_code:"KBL"},
      {name: "Armenia", currency_name: "Armenian Dram", capital: "Yerevan", airport_code: "EVN"},
      {name: "Azerbaijan", currency_name: "Manat", capital: "Baku", airport_code: "GYD"},
      {name: "Bahrain", currency_name: "Bahraini Dinar", capital: "al-Manama", airport_code: "BAH"},
      {name: "Bangladesh", currency_name: "Bangladeshi Taka", capital: "Dhaka", airport_code: "DAC"},
      {name: "Bhutan", currency_name: "Bhutan Ngultrum", capital: "Thimphu", airport_code: "PBH"},
      {name: "Brunei", currency_name: "Brunei Dollar", capital: "Bandar Seri Begawan", airport_code: "BWN"},
      {name: "Cambodia", currency_name: "Kampuchean Riel", capital: "Phnom Penh", airport_code: "PNH"},
      {name: "China", currency_name: "Yuan", capital: "Beijing", airport_code: "PEK"},
      {name: "East Timor", currency_name: "US Dollar", capital: "Dili", airport_code: "DIL"},
      {name: "Georgia", currency_name: "Lari", capital: "Tbilisi", airport_code: "TBS"},
      {name: "India", currency_name: "Rupee", capital: "New Delhi", airport_code: "DEL"},
      {name: "Indonesia", currency_name: "Rupiah", capital: "Jakarta", airport_code: "CGK"},
      {name: "Iran", currency_name: "Iranian Rial", capital: "Tehran", airport_code: "IKA"},
      {name: "Iraq", currency_name: "Iraqi Dinar", capital: "Baghdad", airport_code: "SDA"},
      {name: "Israel", currency_name: "New Shekel", capital: "Jerusalem", airport_code: "TLV"},
      {name: "Japan", currency_name: "Yen", capital: "Tokyo", airport_code: "FUK"},
      {name: "Jordan", currency_name: "Jordanian Dinar", capital: "Amman", airport_code: "AMM"},
      {name: "Kazakstan", currency_name: "Tenge", capital: "Astana", airport_code: "TSE"},
      {name: "Kuwait", currency_name: "Kuwaiti Dinar", capital: "Kuwait", airport_code: "KWI"},
      {name: "Kyrgyzstan", currency_name: "Som", capital: "Bishkek", airport_code: "FRU"},
      {name: "Laos", currency_name: "Kip", capital: "Vientiane", airport_code: "VTE"},
      {name: "Lebanon", currency_name: "Lebanonese Pound", capital: "Beirut", airport_code: "BEY"},
      {name: "Macao", currency_name: "Pataca", capital: "Macao", airport_code: "MFM"},
      {name: "Malaysia", currency_name: "Ringgit", capital: "Kuala Lumpur", airport_code: "KUL"},
      {name: "Maldives", currency_name: "Rufiyaa", capital: "Male", airport_code: "MLE"},
      {name: "Mongolia", currency_name: "Tugrik", capital: "Ulan Bator", airport_code: "ULN"},
      {name: "Myanmar", currency_name: "Kyat", capital: "Rangoon", airport_code: "RGN"},
      {name: "Nepal", currency_name: "Nepalese Rupee", capital: "Kathmandu", airport_code: "KTM"},
      {name: "North Korea", currency_name: "North Korean Won", capital: "Pyonyang", airport_code: ""},
      {name: "Oman", currency_name: "Omani Rial", capital: "Masqat", airport_code: "MCT"},
      {name: "Pakistan", currency_name: "Pakistan Rupee", capital: "Islamabad", airport_code: "KHI"},
      {name: "Philippines", currency_name: "Philippine Peso", capital: "Manila", airport_code: "MNL"},
      {name: "Qatar", currency_name: "Qatari Rial", capital: "Doha", airport_code: "DOH"},
      {name: "Saudi Arabia", currency_name: "Saudi Rial", capital: "Riyadh", airport_code: "JED"},
      {name: "Singapore", currency_name: "Singapore Dollar", capital: "Singapore", airport_code: "SIN"},
      {name: "South Korea", currency_name: "Korean Won", capital: "Seoul", airport_code: "ICN"},
      {name: "Sri Lanka", currency_name: "Sri Lanka Rupee", capital: "Colombo", airport_code: "CMB"},
      {name: "Syria", currency_name: "Syrian Pound", capital: "Damascus", airport_code: "DAM"},
      {name: "Taiwan", currency_name: "Taiwan Dollar", capital: "Taipei", airport_code: "TPE"},
      {name: "Tajikistan", currency_name: "Somoni", capital: "Dushanbe", airport_code: "DYU"},
      {name: "Thailand", currency_name: "Bhaht", capital: "Bangkok", airport_code: "BKK"},
      {name: "Turkey", currency_name: "Lira", capital: "Ankara", airport_code: "IST"},
      {name: "Turkmenistan", currency_name: "Manat", capital: "Ashgabat", airport_code: "ASB"},
      {name: "United Arab Emirates", currency_name: "Dirham", capital: "Abu Dhabi", airport_code: "AUH"},
      {name: "Uzbekistan", currency_name: "Sum", capital: "Toskent", airport_code: "TAS"},
      {name: "Vietnam", currency_name: "Dong", capital: "Hanoi", airport_code: "SGN"},
      {name: "Yemen", currency_name: "Yemeni Rial", capital: "Sanaa", airport_code: "SAH"}
    ],
     "Europe" => [
      {name: "Albania", currency_name: "Albanian Lek", capital: "Tirana", airport_code: "TIA"},
      {name: "Andorra", currency_name: "Euro", capital: "Andorra la Vella", airport_code: "LEU"},
      {name: "Austria", currency_name: "Euro", capital: "Wien", airport_code: "VIE"},
      {name: "Belarus", currency_name: "Belarussian Ruble", capital: "Minsk", airport_code: "MSQ"},
      {name: "Belgium", currency_name: "Euro", capital: "Brussels", airport_code: "BRU"},
      {name: "Bosnia and Herzegovina", currency_name: "Marka", capital: "Sarajevo", airport_code: "SJJ"},
      {name: "Bulgaria", currency_name: "Bulgarian Lev", capital: "Sofia", airport_code: "SOF"},
      {name: "Croatia", currency_name: "Kuna", capital: "Zagreb", airport_code: "SPU"},
      {name: "Cyprus", currency_name: "Euro", capital: "Nicosia", airport_code: "LCA"},
      {name: "Czech Republic", currency_name: "Koruna", capital: "Prauge", airport_code: "PRG"},
      {name: "Denmark", currency_name: "Danish Krone", capital: "Copenhagen", airport_code: "CPH"},
      {name: "England", currency_name: "Pound", capital: "London", airport_code: "LHR"},
      {name: "Estonia", currency_name: "Euro", capital: "Tallinn", airport_code: "TLL"},
      {name: "Finland", currency_name: "Euro", capital: "Helsinki", airport_code: "HEL"},
      {name: "France", currency_name: "Euro", capital: "Paris", airport_code: "CDG"},
      {name: "Germany", currency_name: "Euro", capital: "Berlin", airport_code: "TXL"},
      {name: "Gibraltar", currency_name: "Gibraltar Pound", capital: "Gibraltar", airport_code: "GIB"},
      {name: "Greece", currency_name: "Euro", capital: "Athens", airport_code: "ATH"},
      {name: "Hungary", currency_name: "Forint", capital: "Budapest", airport_code: "BUD"},
      {name: "Iceland", currency_name: "Iceland Krona", capital: "Reykjav", airport_code: "RKV"},
      {name: "Ireland", currency_name: "Ireland", capital: "Dublin", airport_code: "DUB"},
      {name: "Italy", currency_name: "Euro", capital: "Roma", airport_code: "FCO"},
      {name: "Latvia", currency_name: "Euro", capital: "Riga", airport_code: "RIX"},
      {name: "Liechtenstein", currency_name: "Swiss Franc", capital: "Vaduz", airport_code: "ACH"},
      {name: "Lithuania", currency_name: "Euro", capital: "Vilnius", airport_code: "VNO"},
      {name: "Luxembourg", currency_name: "Euro", capital: "Luxembourg", airport_code: "LUX"},
      {name: "Macedonia", currency_name: "Denar", capital: "Skopje", airport_code: "SKG"},
      {name: "Malta", currency_name: "Euro", capital: "Valletta", airport_code: "MLA"},
      {name: "Martinique", currency_name: "Euro", capital: "Fort-de-France", airport_code: "FDF"},
      {name: "Moldova", currency_name: "Moldovan Leu", capital: "Chisinau", airport_code: "KIV"},
      {name: "Monaco", currency_name: "Euro", capital: "Monaco-Ville", airport_code: "NCE"},
      {name: "Montenegro", currency_name: "Euro", capital: "Podgorica", airport_code: "TGD"},
      {name: "Netherlands", currency_name: "Euro", capital: "Amsterdam", airport_code: "AMS"},
      {name: "Northern Ireland", currency_name: "Pound", capital: "Belfast", airport_code: "BFS"},
      {name: "Norway", currency_name: "Euro", capital: "Oslo", airport_code: "OSL"},
      {name: "Poland", currency_name: "Zloty", capital: "Warszawa", airport_code: "WAW"},
      {name: "Portugal", currency_name: "Euro", capital: "Lisboa", airport_code: "LIS"},
      {name: "Romania", currency_name: "Romanian Leu", capital: "Bucharest", airport_code: "OTP"},
      {name: "Russia", currency_name: "Ruble", capital: "Moscow", airport_code: "SVO"},
      {name: "San Marino", capital: "City of San Marino", currency_name: "Euro", airport_code: "RMI"},
      {name: "Scotland", currency_name: "Pound", capital: "Edinburgh", airport_code: "EDI"},
      {name: "Serbia", currency_name: "Serbian Dinar", capital: "Belgrade", airport_code: "BEG"},
      {name: "Slovakia", currency_name: "Euro", capital: "Bratislava", airport_code: "BTS"},
      {name: "Slovenia", currency_name: "Euro", capital: "Ljubljana", airport_code: "LJU"},
      {name: "Spain", currency_name: "Euro", capital: "Madrid", airport_code: "MAD"},
      {name: "Sweden", currency_name: "Swedish Krona", capital: "Stockholm", airport_code: "ARN"},
      {name: "Switzerland", currency_name: "Euro", capital: "Bern", airport_code: "ZRH"},
      {name: "Ukraine", currency_name: "Hryvnia", capital: "Kyiv", airport_code: "KBP"},
      {name: "United Kingdom", currency_name: "Pound", capital: "London", airport_code: "LHR"}
    ],
    "North America" => [
     {name: "Canada", currency_name: "Canadian Dollar", capital: "Ottawa", airport_code: "YYZ"},
     {name: "Greenland", currency_name: "Danish Krone", capital: "Nuuk", airport_code: "GOH"},
     {name: "United States", currency_name: "US Dollar", capital: "Washington", airport_code: "JFK"},
     {name: "Mexico", currency_name: "Mexican Peso", capital: "Mexico City", airport_code: "MEX"}
    ],
    "Central America" => [
      {name: "Anguilla", currency_name: "East Caribbean Dollar", capital: "The Valley", airport_code: "AXA"},
      {name: "Antigua and Barbuda", currency_name: "East Caribbean Dollar", capital: "Saint John's", airport_code: "ANU"},
      {name: "Aruba", currency_name: "Aruban Guilder", capital: "Oranjestad", airport_code: "AUA"},
      {name: "Bahamas", currency_name: "Bahamian Dollar", capital: "Nassau", airport_code: "FPO"},
      {name: "Barbados", currency_name: "Barbados Dollar", capital: "Bridgetown", airport_code: "BGI"},
      {name: "Belize", currency_name: "Belize Dollar", capital: "Belmopan", airport_code: "BDA"},
      {name: "Bermuda", currency_name: "Bermudian Dollar", capital: "Hamilton", airport_code: "BDA"},
      {name: "Cuba", currency_name: "Cuban Peso", capital: "Havana", airport_code: "BZE"},
      {name: "Curacao", currency_name: "Netherlands Antillean Guilder", capital: "Willemstad", airport_code: "CUR"},
      {name: "Costa Rica", currency_name: "Costa Rican Colón", capital: "San Jose", airport_code: "SJO"},
      {name: "Dominica", currency_name: "Eastern Caribbean Dollar", capital: "Roseau", airport_code: "DOM"},
      {name: "Dominican Republic", currency_name: "Dominican Peso", capital: "Santo Domingo de Guzm", airport_code: "PUJ"},
      {name: "El Salvador", currency_name: "US Dollar", capital: "San Salvador", airport_code: "SAL"},
      {name: "Grenada", currency_name: "Eastern Caribbean Dollar", capital: "Saint George's", airport_code: "GND"},
      {name: "Guatemala", currency_name: "Quetzal", capital: "Ciudad de Guatemala", airport_code: "GUA"},
      {name: "Haiti", currency_name: "Gourde", capital: "Port-au-Prince", airport_code: "PAP"},
      {name: "Honduras", currency_name: "Lempira", capital: "Tegucigalpa", airport_code: "TGU"},
      {name: "Jamaica", currency_name: "Jamaican Dollar", capital: "Kingston", airport_code: "KIN"},
      {name: "Nicaragua", currency_name: "Córdoba", capital: "Managua", airport_code: "MGA"},
      {name: "Panama", currency_name: "Balboa", capital: "Panama City", airport_code: "PTY"},
      {name: "Puerto Rico", currency_name: "US Dollar", capital: "San Juan", airport_code: "SJU"},
      {name: "Saint Kitts and Nevis", currency_name: "Eastern Caribbean Dollar", capital: "Basseterre", airport_code: "SKB"},
      {name: "Saint Lucia", currency_name: "Eastern Caribbean Dollar", capital: "Castries", airport_code: "UVF"},
      {name: "Saint Vincent and the Grenadines", currency_name: "Eastern Caribbean Dollar", capital: "Kingstown", airport_code: "SVD"},
      {name: "Trinidad and Tobago", currency_name: "Trinidad and Tobago Dollar", capital: "Port-of-Spain", airport_code: "POS"},
      {name: "Turks and Caicos Islands", currency_name: "US Dollar", capital: "Cockburn Town", airport_code: "PLS"},
      {name: "British Virgin Islands", currency_name: "US Dollar", capital: "Road Town", airport_code: "EIS"},
      {name: "US Virgin Islands", currency_name: "US Dollar", capital: "Charlotte Amalie", airport_code: "STT "}
    ],
      "South America" => [
      {name: "Argentina", currency_name: "Argentine Peso", capital: "Buenos Aires", airport_code: "EZE"},
      {name: "Bolivia", currency_name: "Boliviano", capital: "La Paz", airport_code: "LPB"},
      {name: "Brazil", currency_name: "Brazilian Real", capital: "Brasília", airport_code: "GRU"},
      {name: "Chile", currency_name: "Chilean Peso", capital: "Santiago", airport_code: "SCL"},
      {name: "Colombia", currency_name: "Columbian Peso", capital: "Bogota", airport_code: "BOG"},
      {name: "Ecuador", currency_name: "US Dollar", capital: "Quito", airport_code: "UIO"},
      {name: "Guyana", currency_name: "Guyanese Dollar", capital: "Georgetown", airport_code: "GEO"},
      {name: "Paraguay", currency_name: "Guaraní", capital: "Asunci", airport_code: "ASU"},
      {name: "Peru", currency_name: "Sol", capital: "Lima", airport_code: "LIM"},
      {name: "Uruguay", currency_name: "Uruguayan Peso", capital: "Montevideo", airport_code: "MVD"},
      {name: "Venezuela", currency_name: "Bolivar", capital: "Caracas", airport_code: "CCS"}
  ],
      "Oceania" => [
      {name: "Australia", currency_name: "Australian Dollar", capital: "Canberra", airport_code: "SYD"},
      {name: "Fiji", currency_name: "Fijian Dollar", capital: "Suva", airport_code: "NAM"},
      {name: "French Polynesia", currency_name: "CFP Franc", capital: "Papeete", airport_code: "PPT"},
      {name: "Guam", currency_name: "US Dollar", capital: "Aga", airport_code: "GUM"},
      {name: "Kiribati", currency_name: "Kiribati Dollar", capital: "South Tarawa", airport_code: "TRW"},
      {name: "Federated States of Micronesia", currency_name: "US Dollar", capital: "Palikir", airport_code: "PNI"},
      {name: "Nauru", currency_name: "Australian Dollar", capital: "Yaren", airport_code: "INU"},
      {name: "New Caledonia", currency_name: "CFP Franc", capital: "Noum", airport_code: "NOU"},
      {name: "New Zealand", currency_name: "New Zealand Dollar", capital: "Wellington", airport_code: "AKF"},
      {name: "Niue", currency_name: "New Zealand Dollar", capital: "Alofi", airport_code: "IUE"},
      {name: "Palau", currency_name: "US Dollar", capital: "Koror", airport_code: "ROR"},
      {name: "Papua New Guinea", currency_name: "Kina", capital: "Port Moresby", airport_code: "POM"},
      {name: "Samoa", currency_name: "Tala", capital: "Apia", airport_code: "APW"},
      {name: "Solomon Islands", currency_name: "Solomon Islands Dollar", capital: "Honiara", airport_code: "HIR"},
      {name: "Suriname", currency_name: "Surinamese Dollar", capital: "Paramaribo", airport_code: "PBM"},
      {name: "Tokelau", currency_name: "New Zealand Dollar", capital: "Fakaofo", airport_code: "APW"},
      {name: "Tonga", currency_name: "Paʻanga", capital: "Nuku'alofa", airport_code: "TBU"},
      {name: "Tuvalu", currency_name: "Tuvaluan Dollar", capital: "Funafuti", airport_code: "FUN"},
      {name: "Vanuatu", currency_name: "Vatu", capital: "Port-Vila", airport_code: "VLI"}
    ]
  }


COUNTRIES.each_pair do |continent, countries|
  countries.each do |country|
    Country.create(name: country[:name], continent: continent.to_s, currency_name: country[:currency_name], capital: country[:capital], airport_code: country[:airport_code])
  end
end
